export function getMarketSignals() {
  return {
    updated: new Date().toISOString(),
    overview: {
      btc: { price: '$64,700', change: '+0.9%', note: '突破下降趋势线' },
      eth: { price: '$1,910', change: '+1.8%', note: '站上$1,900, EIP-8361催化' },
      bnb: { price: '$606', change: '+1.2%', note: '延续强势' },
      sol: { price: '$74.5', change: '+0.5%', note: '弱势跟涨, ETF零流入' },
      xau: { price: '$4,265', change: '+4.14%', note: '单日暴涨200美金, 突破震荡区间' },
      totalMcap: '~$2.29T (+1.2%)',
      btcDominance: '56.5%',
      fearGreed: '17 (极度恐惧->谨慎乐观)',
    },
    tradingSignals: [
      {
        coin: 'BTC', bias: '多头占优', color: 'amber',
        support: '$63,500 -> $62,600 -> $62,000',
        resistance: '$65,250 -> $67,300 -> $70,800',
        strategy: '回踩$64,000-64,400不破可试多, 目标$65,250; 突破站稳$65,000可看$67,000. 跌破$63,500减仓.',
      },
      {
        coin: 'ETH', bias: '领涨, 结构最清晰', color: 'blue',
        support: '$1,885 -> $1,800 -> $1,788',
        resistance: '$1,918 (100日均线) -> $2,000 -> $2,074',
        strategy: '等回踩$1,900附近不破再进场, 止损$1,885下方, 目标$1,931. MACD强买入信号.',
      },
      {
        coin: 'SOL', bias: '最弱, 观望', color: 'gray',
        support: '$73.84 -> $73.07',
        resistance: '$74.57',
        strategy: '不做多, 等方向选择. 跌破$73.84可右侧跟空. 美国SOL ETF连续5日零流入.',
      },
      {
        coin: 'XAU/USD', bias: '突破走强, 短线超买', color: 'amber',
        support: '$4,255 -> $4,220 -> $4,200 -> $4,165',
        resistance: '$4,300 -> $4,345 -> $4,400 -> $4,500',
        strategy: '昨日单日暴涨200美金(+4.14%), 突破持续数月的震荡区间. 短线RSI超买严重. 回踩$4,255-4,220不破可试多, 目标$4,300->4,345. 跌破$4,200止损. 100日/200日均线死叉仍存, 反弹视为阶段性. 中期若站稳$4,300可看$4,500.',
      },
    ],
    tokenUnlocks: [
      { token: 'GoldFinger (GF)', date: '8/6 (今日)', amount: '$11.52M', pct: '5.05%', risk: 'high' },
      { token: 'INFINIT (IN)', date: '8/7', amount: '$2.31M', pct: '20.30%', risk: 'high' },
      { token: 'STABLE', date: '8/8', amount: '$28.75M', pct: '3.55%', risk: 'medium' },
      { token: 'NAME', date: '8/9', amount: '$48.47M', pct: '74.54%', risk: 'extreme' },
      { token: 'MOVE', date: '8/9', amount: '$1.22M', pct: '3.90%', risk: 'medium' },
      { token: 'LAYER', date: '8/12', amount: '-', pct: '12.89%', risk: 'high' },
      { token: 'BB (BounceBit)', date: '8/12', amount: '-', pct: '9.04%', risk: 'high' },
      { token: 'APT (Aptos)', date: '8/12', amount: '-', pct: '-', risk: 'medium' },
    ],
    newListings: [
      { token: '2U2/USDT', exchange: 'MEXC', status: '已上线' },
      { token: 'PALCOIN/USDT', exchange: 'MEXC', status: '已上线' },
      { token: 'GIGADEV 永续', exchange: 'Binance', status: '已上线' },
      { token: 'OFFICIAL / JORDAN', exchange: 'Gate Alpha', status: '已上线' },
    ],
    trendingTokens: [
      { token: 'HOOD (Robinhood)', change: '+445%', tag: 'meme', note: '纯炒作, 极高风险' },
      { token: 'CASHCAT', change: '+25.54%', tag: 'meme', note: '月涨幅+1896%' },
      { token: 'HOME', change: '+30%', tag: '上币传闻', note: '传Upbit将上线' },
      { token: 'ZEC (Zcash)', change: '+26.67%', tag: '隐私币', note: '隐私叙事回暖' },
      { token: 'ZRO (LayerZero)', change: '+19.30%', tag: '跨链', note: '跨链协议热度上升' },
      { token: 'UNI (Uniswap)', change: '+8.68%', tag: 'DeFi', note: '手续费新规落地' },
      { token: 'HYPE (Hyperliquid)', change: '+4.2%', tag: 'DeFi', note: '永续合约DEX龙头' },
      { token: 'TAO (Bittensor)', change: '-', tag: 'AI', note: 'AI赛道龙头, ETF预期' },
      { token: 'PUMP (Pump.fun)', change: '+8.18%', tag: 'meme', note: 'meme平台代币' },
    ],
    keyEvents: [
      { event: '黄金单日暴涨4.14%, 突破震荡区间', time: '8/5', impact: '宏观' },
      { event: 'BTC站稳$64,500下降趋势线', time: '今日确认', impact: '趋势' },
      { event: 'ETH $1,920突破 (100日均线)', time: '今日', impact: '趋势' },
      { event: '美国初请失业金人数', time: '8/6 (今晚)', impact: '宏观' },
      { event: '美国CPI数据公布', time: '8/12', impact: '宏观' },
      { event: 'Jackson Hole央行年会', time: '8月下旬', impact: '宏观' },
      { event: 'Ethereum Glamsterdam升级', time: 'Q3-Q4', impact: '生态' },
    ],
    narratives: [
      { name: '黄金避险', tokens: 'XAU, PAXG', desc: '金价突破$4,200, 单日暴涨4%. 美联储9月降息预期升温, 美元走弱. BTC/黄金比率15.12oz, 历史低位区间' },
      { name: 'AI赛道', tokens: 'TAO, Bittensor', desc: '去中心化AI网络, 2026年可能有ETF相关预期' },
      { name: 'DeFi', tokens: 'HYPE, UNI', desc: 'Hyperliquid回购销毁机制; Uniswap手续费新规' },
      { name: 'Meme', tokens: 'HOOD, CASHCAT, PUMP', desc: '纯情绪驱动, 快进快出' },
      { name: 'ETH生态', tokens: 'ETH, EIP-8361', desc: '质押销毁提案 + Glamsterdam升级预期' },
      { name: 'Layer 1', tokens: 'SOL, SUI', desc: 'SOL Alpenglow共识升级; SUI生态扩张' },
    ],
  };
}
